//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detai()
        {
            this.Phieugiaodetais = new HashSet<Phieugiaodetai>();
        }
    
        public int MADT { get; set; }
        public string TENDT { get; set; }
        public string MOTADT { get; set; }
        public string NGUOIDENGHIDT { get; set; }
        public string TRANGTHAIDT { get; set; }
        public Nullable<System.DateTime> NGAYDTHIEULUC { get; set; }
        public int MALDT { get; set; }
    
        public virtual LoaiDT LoaiDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieugiaodetai> Phieugiaodetais { get; set; }
    }
}
