//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giangvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giangvien()
        {
            this.Phieuchamdiems = new HashSet<Phieuchamdiem>();
            this.Phieugiaodetais = new HashSet<Phieugiaodetai>();
        }
    
        public string MAGV { get; set; }
        public string HOGV { get; set; }
        public string TENGV { get; set; }
        public string QUEQUAN { get; set; }
        public string ANHDAIDIEN { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public bool GIOITINH { get; set; }
        public string MOTA { get; set; }
        public string TRANGTHAIGV { get; set; }
        public Nullable<int> MADV { get; set; }
        public Nullable<int> MACV { get; set; }
        public int MAHV { get; set; }
        public Nullable<int> MACN { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Chucvu Chucvu { get; set; }
        public virtual Chuyennganh Chuyennganh { get; set; }
        public virtual Donvi Donvi { get; set; }
        public virtual Hocvi Hocvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieuchamdiem> Phieuchamdiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieugiaodetai> Phieugiaodetais { get; set; }
    }
}
