//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISchoolEntities : DbContext
    {
        public ISchoolEntities()
            : base("name=ISchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_Phieutheodoi> CT_Phieutheodoi { get; set; }
        public virtual DbSet<Chucvu> Chucvus { get; set; }
        public virtual DbSet<Chuyennganh> Chuyennganhs { get; set; }
        public virtual DbSet<Chuyennganh_Monhoc> Chuyennganh_Monhoc { get; set; }
        public virtual DbSet<Detai> Detais { get; set; }
        public virtual DbSet<Donvi> Donvis { get; set; }
        public virtual DbSet<Giangvien> Giangviens { get; set; }
        public virtual DbSet<Hocvi> Hocvis { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LoaiDT> LoaiDTs { get; set; }
        public virtual DbSet<Monhoc> Monhocs { get; set; }
        public virtual DbSet<Nguoidung> Nguoidungs { get; set; }
        public virtual DbSet<PCD_Tieuchi> PCD_Tieuchi { get; set; }
        public virtual DbSet<Phieuchamdiem> Phieuchamdiems { get; set; }
        public virtual DbSet<Phieugiaodetai> Phieugiaodetais { get; set; }
        public virtual DbSet<Phieutheodoi> Phieutheodois { get; set; }
        public virtual DbSet<Sinhvien> Sinhviens { get; set; }
        public virtual DbSet<Tieuchi> Tieuchis { get; set; }
    }
}
