//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCD_Tieuchi
    {
        public int SoPCD { get; set; }
        public int MATC { get; set; }
        public Nullable<double> Diem { get; set; }
        public string NhanXet { get; set; }
    
        public virtual Phieuchamdiem Phieuchamdiem { get; set; }
        public virtual Tieuchi Tieuchi { get; set; }
    }
}
