//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieutheodoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieutheodoi()
        {
            this.CT_Phieutheodoi = new HashSet<CT_Phieutheodoi>();
        }
    
        public int SoPTDTD { get; set; }
        public int SoPGDT { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public string HinhThuc_Gap_GV { get; set; }
        public Nullable<int> MUCDO_HOANTHANH_CHUNG { get; set; }
        public Nullable<double> DIEM_THEODOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_Phieutheodoi> CT_Phieutheodoi { get; set; }
        public virtual Phieugiaodetai Phieugiaodetai { get; set; }
    }
}
