//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieuchamdiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieuchamdiem()
        {
            this.PCD_Tieuchi = new HashSet<PCD_Tieuchi>();
        }
    
        public int SoPCD { get; set; }
        public int SoPGDT { get; set; }
        public Nullable<System.DateTime> NgayCham { get; set; }
        public string VaitroGV { get; set; }
        public Nullable<double> DiemTong { get; set; }
        public string NhanXet { get; set; }
        public string MAGV { get; set; }
    
        public virtual Giangvien Giangvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCD_Tieuchi> PCD_Tieuchi { get; set; }
        public virtual Phieugiaodetai Phieugiaodetai { get; set; }
    }
}
