//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieugiaodetai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieugiaodetai()
        {
            this.Phieuchamdiems = new HashSet<Phieuchamdiem>();
            this.Phieutheodois = new HashSet<Phieutheodoi>();
        }
    
        public int SoPGDT { get; set; }
        public Nullable<System.DateTime> Ngaygiao { get; set; }
        public Nullable<System.DateTime> Hannop { get; set; }
        public string MASV { get; set; }
        public int MADT { get; set; }
        public string MAGV { get; set; }
    
        public virtual Detai Detai { get; set; }
        public virtual Giangvien Giangvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieuchamdiem> Phieuchamdiems { get; set; }
        public virtual Sinhvien Sinhvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieutheodoi> Phieutheodois { get; set; }
    }
}
