//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinhvien()
        {
            this.Phieugiaodetais = new HashSet<Phieugiaodetai>();
        }
    
        public string MASV { get; set; }
        public string HOSV { get; set; }
        public string TENSV { get; set; }
        public string ANHDAIDIEN { get; set; }
        public string QUEQUAN { get; set; }
        public Nullable<System.DateTime> NGAYSINHSV { get; set; }
        public string CMNDSV { get; set; }
        public Nullable<double> DIEM_TBTL { get; set; }
        public string SDTSV { get; set; }
        public string SDT_PHUHUYNH { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI_SV { get; set; }
        public string DIACHI_THUONGTRU { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string TRANGTHAISV { get; set; }
        public Nullable<int> MACN { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Chuyennganh Chuyennganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieugiaodetai> Phieugiaodetais { get; set; }
    }
}
